---
title: "git_00"
author: "Thelma Means"
date: "Summer 2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with a sequence of commits to the master branch.
Our project will be done using several commits to the master branch.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->
'Twas brillig, and the slithy toves  
Did gyre and gimble in the wabe:  
All mimsy were the borogoves,  
And the mome raths outgrabe.  
'Beware the Jabberwock, my son!  

## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->
Now close the windows and hush all the fields:  
If the trees must, let them silently toss;  
No bird is singing now, and if there is,  
Be it my loss.  

It will be long ere the marshes resume  


## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->
The sun was shining on the sea,  
      Shining with all his might:  
He did his very best to make  
      The billows smooth and bright —  
And this was odd, because it was  
      The middle of the night.  

The moon was shining sulkily,  
      Because she thought the sun  
Had got no business to be there  
      After the day was done —  
"It's very rude of him," she said  ,
      "To come and spoil the fun  

## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->
Pretty women wonder where my secret lies.  
I’m not cute or built to suit a fashion model’s size     
But when I start to tell them,  
They think I’m telling lies.  
I say,  
It’s in the reach of my arms,  
The span of my hips,     
The stride of my step,     
The curl of my lips.     
I’m a woman  
Phenomenally.  
Phenomenal woman,     
That’s me.  

I walk into a room  
Just as cool as you please,     
And to a man,  
The fellows stand or  
Fall down on their knees.     
Then they swarm around me,  
A hive of honey bees.     
I say,  
It’s the fire in my eyes,     
And the flash of my teeth,     
The swing in my waist,     
And the joy in my feet.  
